name: Activate
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: Request manual activation 🔑
    runs-on: ubuntu-latest
    steps:
      # Request manual activation file
      - name: Unity - Activate
        uses: game-ci/unity-activate@v1.3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
