name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('UnityGameServer/Assets/**', 'UnityGameServer/Packages/**', 'UnityGameServer/ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: UnityGameServer
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Upload Test Results
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts
